insert into cozinha (id, nome) values (1, 'Tailandesa')
insert into cozinha (id, nome) values (2, 'Inidiana')
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Thai Gourmet', 10, 1)
insert into restaurante (nome, taxa_frete, cozinha_id) value ('Thai Delivery', 9.50, 1)
insert into restaurante (nome, taxa_frete, cozinha_id) value ('Tuk Tuk Comida Indiana', 15, 2)
insert into estado (nome) values ("Acre")
insert into estado (nome) values ("Alagoas")
insert into estado (nome) values ("Amapá")
insert into estado (nome) values ("Amazonas")
insert into estado (nome) values ("Bahia")
insert into estado (nome) values ("Ceará")
insert into estado (nome) values ("Distrito Federal")
insert into estado (nome) values ("Epirito Santo")
insert into estado (nome) values ("Pará")
insert into estado (nome) values ("Paraná")

