insert into cozinha (id, nome) values (1, 'Tailandesa')
insert into cozinha (id, nome) values (2, 'Inidiana')
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Thai Gourmet', 10, 1)
insert into restaurante (nome, taxa_frete, cozinha_id) value ('Thai Delivery', 9.50, 1)
insert into restaurante (nome, taxa_frete, cozinha_id) value ('Tuk Tuk Comida Indiana', 15, 2)
insert into estado (id, nome) values (1, "Acre")
insert into estado (id, nome) values (2, "Alagoas")
insert into estado (id, nome) values (3, "São Paulo")
insert into cidade (id, nome, estado_id) values (1, "São Paulo", 3)

